<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Estatística
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Média e Variância;</li>
  <li>Ordem e Posição;</li>
  <li>Correlação.</li>
</ol>

---

# **Exercícios**

## 1\. Tráfego de São Paulo

Neste exercício, vamos continuar a analisar os dados de mobilidade urbana da cidade de São Paulo. A base de dados está neste [link](https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv) e é uma copia do dado original, presente neste [link](https://archive.ics.uci.edu/ml/datasets/Behavior+of+the+urban+traffic+of+the+city+of+Sao+Paulo+in+Brazil). A base de dados contem a quantidade de acidentes ocorridos na cidade entre 14/12/09 e 18/12/09, das 07:00h ás 20:00h, agregados em intervalos de 30 minutos.

In [1]:
!wget -q "https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv" -O traffic.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('traffic.csv', sep=';')

In [4]:
df.head()

hour  bus_stoped  broken_truck  vehicle_excess  accident_victim  \
0     1           0             0               0                0   
1     2           0             0               0                0   
2     3           0             0               0                0   
3     4           0             0               0                0   
4     5           0             0               0                0   

   running_over  fire_vehicles  occurrence_freight  \
0             0              0                   0   
1             0              0                   0   
2             0              0                   0   
3             0              0                   0   
4             0              0                   0   

   incident__dangerous_freight  lack_electricity  fire  flooding  \
0                            0                 0     0         0   
1                            0                 0     0         0   
2                            0                 0     0         0   
3                            0                 0     0         0   
4                            0                 0     0         0   

   manifestations  defect_trolleybuses  tree_road  semaphore_off  \
0               0                    0          0              0   
1               0                    0          0              0   
2               0                    0          0              0   
3               0                    0          0              0   
4               0                    0          0              0   

   intermittent_emaphore slowness_traffic_%  
0                      0                4,1  
1                      0                6,6  
2                      0                8,7  
3                      0                9,2  
4                      0               11,1

- **Exemplo**: (para relembrar)

O código abaixo extrai a 13ª linha do arquivo que representa a 14ª meia hora do dia 14/12/09, contadas a partir das 07:00h, ou seja, todos os incidentes ocorridos na cidade no dia em questão entre as 13:30h e 14:00h. Vemos, por exemplo, que dois ônibus e dois caminhões ficaram paradados nas ruas da cidade, atrapalhando o tráfego.

In [5]:
df.iloc[[11]]

hour  bus_stoped  broken_truck  vehicle_excess  accident_victim  \
11    12           0             1               0                0   

    running_over  fire_vehicles  occurrence_freight  \
11             0              0                   0   

    incident__dangerous_freight  lack_electricity  fire  flooding  \
11                            0                 0     0         0   

    manifestations  defect_trolleybuses  tree_road  semaphore_off  \
11               0                    0          0              0   

    intermittent_emaphore slowness_traffic_%  
11                      0                4,7

### **1.1. Agregação** 

Neste primeira atividade, você deve gerar um array NumPy por dia. Para cada array você deve somar todos os incidentes que aconteceram naquela meia hora. Sendo assim, cada array deve ter 27 posições, cada qual com a soma dos incidentes daquela meira hora.

**Dica**: Você deve remover a primeira e a última coluna.

**Dica**: Os arrays devem ter os seguintes valores:

```python
14: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 3]
15: [3, 0, 0, 0, 2, 4, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 4, 7, 6, 3, 0, 1, 1, 5, 4, 6, 0]
16: [1, 1, 2, 4, 4, 5, 3, 2, 4, 2, 1, 1, 3, 6, 2, 0, 2, 8, 4, 6, 4, 1, 2, 7, 15, 4, 0]
17: [4, 1, 1, 0, 0, 0, 2, 3, 2, 7, 2, 1, 7, 3, 6, 4, 3, 2, 2, 3, 2, 5, 2, 0, 1, 4, 15]
18: [10, 1, 1, 5, 5, 7, 3, 4, 3, 1, 2, 3, 2, 2, 6, 2, 2, 4, 2, 3, 0, 3, 3, 2, 3, 6, 0]
```

In [ ]:
# resposta da questão 1.1

In [30]:
Dia_14 = np.array(df.iloc[0:27,1:-1]).sum(axis=1)
Dia_14


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 2, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 2, 2, 3])

In [13]:
Dia_15 = np.array(df.iloc[27:54,1:-1]).sum(axis=1)
Dia_15

array([3, 0, 0, 0, 2, 4, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 4, 7, 6, 3, 0, 1,
       1, 5, 4, 6, 0])

In [16]:
Dia_16 = np.array(df.iloc[54:81,1:-1]).sum(axis=1)
Dia_16

array([ 1,  1,  2,  4,  4,  5,  3,  2,  4,  2,  1,  1,  3,  6,  2,  0,  2,
        8,  4,  6,  4,  1,  2,  7, 15,  4,  0])

In [20]:
Dia_17 = np.array(df.iloc[81:108,1:-1]).sum(axis=1)
Dia_17

array([ 4,  1,  1,  0,  0,  0,  2,  3,  2,  7,  2,  1,  7,  3,  6,  4,  3,
        2,  2,  3,  2,  5,  2,  0,  1,  4, 15])

In [23]:
Dia_18 = np.array(df.iloc[108:135,1:-1]).sum(axis=1)
Dia_18

array([10,  1,  1,  5,  5,  7,  3,  4,  3,  1,  2,  3,  2,  2,  6,  2,  2,
        4,  2,  3,  0,  3,  3,  2,  3,  6,  0])

In [15]:
Dia_14.sum()

16

In [14]:
Dia_15.sum()

63

In [19]:
Dia_16.sum()

94

In [21]:
Dia_17.sum()

82

In [24]:
Dia_18.sum()

85

In [6]:
incidentes = np.array(df.iloc[0:135,1:-1]).sum(axis=1)

In [7]:
incidentes.sum()

340

### **1.2. Métricas** 

Para cada array você deve calcular as seguintes métricas: 

 - **média**;
 - **desvio padrão**.

In [ ]:
# resposta da questão 1.2

In [65]:
Média_14 =  np.mean(Dia_14)
Desvio_14 = np.std(Dia_14)


Média_15 = np.mean(Dia_15)
Desvio_15 = np.std(Dia_15)


Média_16 = np.mean(Dia_16)
Desvio_16 = np.std(Dia_16)

Média_17 = np.mean(Dia_17)
Desvio_17 = np.std(Dia_17)

Média_18 = np.mean(Dia_18)
Desvio_18 = np.std(Dia_18)


#Média Dias:

In [61]:
Média_14

0.5925925925925926

In [51]:
Média_15

3.1481481481481484

In [52]:
Média_16

3.4814814814814814

In [53]:
Média_17

3.037037037037037

In [56]:
Média_18

3.1481481481481484

#Desvio Padrão


In [66]:
Desvio_14

1.1944085553034889

In [67]:
Desvio_15

2.0184335693983275

In [68]:
Desvio_16

3.047407767514698

In [69]:
Desvio_17

3.0487578707046925

In [70]:
Desvio_18

2.1892617342417258

### **1.3. Interpretação** 

> Qual dia apresenta a maior média de acidentes por meia hora?

**Resposta:** Dia 16

> Qual dia apresenta a menor variação de acidentes por meia hora?

**Resposta:** Dia 14

---